### PR TITLE
Containerize mofid package

### PR DESCRIPTION
**Pull request by bbucior**
Hello @arosen93 I finished the Docker and singularity experiments! Our setup requirements are now much shorter (though there might be cluster-specific instructions users need to follow to get set up with singularity on their HPC environment).

The link to the .sif file in the README points to the future location for a tagged GitHub release. In the meantime, I've published a [pre-release](https://github.com/snurr-group/mofid/releases/tag/draft-docker) file (and will delete and rerelease once we finalize the PR).

I've only been able to test out the code on my laptop so far. Would you be able to test on HPC? Any other feedback would be appreciated, too! Thanks for your help.

### CODE REVIEW

**Comment by arosen93** [comment]
Beautiful!! I'll try it out tonight and respond more here. Stay tuned.

**Comment by arosen93** [comment]
One general suggestion before I begin. I would recommend that we not de-emphasize the existing installation and usage instructions. I know personally, I would always prefer to run things without Docker so would be a bit scared off by the instruction as-written. People might be a bit confused too if they are coming back to use MOFid after some time away. I would propose that we keep the README basically as it currently is but add a new section for Docker. What are your thoughts about this?

**Comment by arosen93** [comment]
I was able to get everything to run on HPC without any issue! Here is a suggestion for an updated README: https://github.com/arosen93/mofid/blob/rosen-docker/README.md

**Comment by bbucior** [comment]
Great point about user preferences. I really like your updated READMEs and how clean all of the setup and usage instructions are presented--thanks for simplifying those docs! I'll issue a new release and SIF after this PR and yours are merged.

**Comment by arosen93** [comment]
Great! I was pleasantly surprised by how easy the singularity container was to use. Thanks for putting that together! I'll merge the README PR when the test passes.

**Pull request merged**
